openapi: 3.0.0
info:
  title: STM Medical API Documentation
  description: |
    <div style="background-color: #f1f1f1; padding: 20px; border-radius: 5px;">
      <h1 style="color: #333;">Welcome to the STM Medical API Documentation!</h1>
      <p style="font-size: 16px;">Explore the power of our API to make a difference.</p>
      <p style="font-weight: bold;">Organization: Service To Mankind</p>
      <hr style="border: none; border-top: 1px solid #ccc; margin: 20px 0;">
      <p style="font-size: 14px;">
        This documentation provides detailed information about the API endpoints and functionality offered by the STM organization.
      </p>
      <p style="font-size: 14px;">
        We aim to empower developers and partners to leverage our services for the betterment of society.
      </p>
    </div>

    <h2 style="color: #333;">Getting Started</h2>
    <p style="font-size: 16px;">To get started, please refer to the sidebar navigation to explore the available endpoints and their respective request and response structures.</p>

    <h2 style="color: #333;">Authentication</h2>
    <p style="font-size: 16px;">Some API endpoints require authentication. Please refer to the authentication section in the sidebar for more information on how to authenticate your requests.</p>

    <div style="background-color: #f9f9f9; padding: 10px; border-radius: 5px;">
      <p style="font-size: 14px; font-weight: bold;">Note:</p>
      <p style="font-size: 14px;">This API is intended for authorized use only. Make sure to obtain the necessary access credentials and follow the guidelines provided.</p>
    </div>
  version: 1.0.0
servers:
  - url: https://apis.stmorg.in/medical
tags:
  - name: Introduction
    description: |

      STM (Service To Mankind) is a non-governmental organization (NGO) that is committed to the development of the society. It is a non-profit organization that aims to provide basic necessities to the underprivileged and help them lead a better life. The NGO is run by a group of volunteers who are passionate about making a difference in the society.

      ## List of API Documentations
      - [STM Management](/)
      - [Medical Management](/medical)
